export const width = (window.innerHeight * 4) / 3;
export const height = window.innerHeight;
export const wallThickness = 4;
export const endGameDuration = 5;
export const backgroundColor = '#e5e5e5';
export const wallColor = '#262626';
export const startColor = '#84cc16';
export const finishColor = '#ef4444';
export const playerColor = '#3b82f6';
